algoritmo "somainteiro"
// Função : somar numeros inteiros
// Autor : fernando da silva
// Data : 04/03/2019
// Seção de Declarações

var

n1,n2,soma : inteiro

inicio

EscrevaL ("Programa que calcula a soma de dois numeros inteiros.")

Escreva ("Digite o primeiro numero inteiro : ")

Leia (n1)

Escreva ("Digite o segundo numero inteiro : ")

Leia(n2)

soma <- (n1+n2)

Escreva ("Total da soma: " ,soma)

fimalgoritmo

