Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/03/2019
Var

SALDO: REAL
NOVOSALDO: REAL
Inicio

ESCREVA ("INFORME O SALDO DA APLICAÇÃO: ")
LEIA (SALDO)
NOVOSALDO<- SALDO*0.011+SALDO
ESCREVA ("O NOVO SALDO É: ",NOVOSALDO)


Fimalgoritmo