Algoritmo "semnome"
// Disciplina   : [Algoritmo e Lógica de Programação] 
// Professor   : Rodrigo Franklin 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/03/2019

Var

{P= PERÍMETRO, R= RAIO, A=AREA}
P,R,A: REAL

Inicio

ESCREVA ("DIGITE O RAIO: ")
LEIA (R)
P<-2*PI*R
ESCREVAL("O PERÍMETRO É:",P)
A<- PI*R^2
ESCREVAL ("A AREA É:     ",A)


Fimalgoritmo