Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/03/2019
Var

D_MENOR,D_MAIOR,AREA: REAL

Inicio
ESCREVA(" INFORME VALOR DA DIAGONAL MAIOR: ")
LEIA (D_MAIOR)
ESCREVA(" INFORME VALOR DA DIAGONAL MENOR: ")
LEIA (D_MENOR)
AREA<- ((D_MAIOR*D_MENOR)/2)
ESCREVA (" A AREA DO LOSANGO É:",AREA)

Fimalgoritmo