Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/03/2019
Var
{SENDO A= ALTURA , R= RAIO , V= VOLUME}
A,R,V:REAL

Inicio

ESCREVA ("INFORME A ALTURA DA LATA: ")
LEIA (A)
ESCREVA ("INFORME O RAIO DA CIRCUNFERÊNCIA DA LATA: ")
LEIA(R)

V<-PI*(R^2)*A
ESCREVA ("VOLUME DA LATA DE OLEO É:",V/1:2:2)

Fimalgoritmo