Algoritmo "semnome"
// Disciplina   : [Algoritmo e Lógica de Programação] 
// Professor   : Rodrigo Franklin 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/03/2019
Var
P: INTEIRO
NP: REAL

Inicio

ESCREVA ("INFORME SEU PESO EM KG: ")
LEIA (P)
ESCREVAL("O SEU PESO INFORMADO EM GRAMAS É: ", P*1000, " GRAMAS")
NP<- P+P*12/100
ESCREVAL("O SEU PESO CASO ENGORDE 12% SERÁ DE : ",NP*1000, " GRAMAS")


Fimalgoritmo