algoritmo "NOME"
// Função :  Crie um algoritmo que imprima na tela o seu nome completo dez vezes.
// Autor : Renan Kalio Alessio Ribeiro
// Data : 07/03/2019
// Seção de Declarações
var
contador: inteiro
nome: caractere
inicio
// Seção de Comandos
Escreva ("Informe o nome completo: ")
leia (nome)
contador <- 0
enquanto contador <= 9 faca
  escreval(nome)
    contador <- contador + 1
fimenquanto
fimalgoritmo

