algoritmo "semnome"
// Função : Crie um algoritmo que leia um número que será o limite superior de um intervalo e o incremento. Imprima todos os números naturais no intervalo de 0 até esse número.
// Autor : Renan Kalio Alessio Ribeiro
// Data : 07/03/2019
// Seção de Declarações
var
contador, n: inteiro
inicio
// Seção de Comandos
escreva ("Informe um numero :")
 leia (n)
 contador <- 0
enquanto contador <= n faca
 escreval(contador)
 contador <- contador + 5
fimenquanto
fimalgoritmo

