algoritmo "somar os numeros pares"
// Função : Crie um algoritmo que apresente a soma dos números pares entre 25 e 200.
// Autor :  Renan kalio
// Data : 09/03/2019
// Seção de Declarações 
var
 i: inteiro
  total: inteiro
inicio
// Seção de Comandos 
para i de 25 ate 200 passo 1 faca
   se (i) mod 2 = 0 entao
     escreval(i)
   fimse
fimpara
    total <- i+i
    escreval ("A soma dos numeros pares sao: ", total)
fimalgoritmo
