algoritmo "UNISMG"
// Função :  Entrar com o número de vezes que deseja que a palavra UNISMG apareça e imprima
// Autor : Renan Kalio Alessio Ribeiro
// Data : 07/03/2019
// Seção de Declarações
var
contador, n: inteiro
inicio
// Seção de Comandos
escreva ("Informe o numero de vezes que a palavra UNISMG será escrita: ")
leia (n)

contador <- 1
enquanto contador <= n faca
  escreval("UNISMG")
    contador <- contador + 1
fimenquanto
fimalgoritmo

