algoritmo "numeros pares de 100 a 0"
// Função : algoritmo que apresente apenas os números pares entre 100 e 0. Exemplo: 100, 98, 96, 04, etc...até o zero.
// Autor : Renan Kalio Alessio Ribeiro
// Data : 07/03/2019
// Seção de Declarações
var
   contador: inteiro
inicio
// Seção de Comandos
contador <- 100
 enquanto (contador >=0) faca
  escreval (contador)
   contador <- contador -2
 fimenquanto

fimalgoritmo
